plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin' version '2.2.0'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly files(rootProject.file(tlm_jar_path))
}

publishMods {
    file = tasks.named('jar').get().archiveFile
    changelog = file("${rootDir}/CHANGELOG.md").exists() ? file("${rootDir}/CHANGELOG.md").text : 'See release notes on GitHub'
    type = STABLE
    modLoaders.add('neoforge')

    curseforge {
        projectId = '1681684'
        accessToken = providers.environmentVariable('CURSEFORGE_TOKEN')
        minecraftVersions.add('1.21')
        displayName = 'Maid File Manager v' + project.version + ' neoforge 1.21'
    }
}